{
 "title": "ASUS RT-AC68U Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "usr",
     "column": "usr",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "select mean(usr) from \"router_cpu\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "usr" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "series": "router_cpu"
    },
    {
     "alias": "sys",
     "column": "sys",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "select mean(sys) from \"router_cpu\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_cpu"
    },
    {
     "alias": "sirq",
     "column": "sirq",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "select mean(sirq) from \"router_cpu\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "sirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_cpu"
    },
    {
     "alias": "irq",
     "column": "irq",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "select mean(irq) from \"router_cpu\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_cpu"
    },
    {
     "alias": "nic",
     "column": "nic",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "select mean(nic) from \"router_cpu\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "nic" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_cpu"
    },
    {
     "alias": "io",
     "column": "io",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "select mean(io) from \"router_cpu\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_cpu"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_loadavg",
     "select": [
      [
       { "params": [ "1min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "5min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_loadavg",
     "select": [
      [
       { "params": [ "5min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "15min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_loadavg",
     "select": [
      [
       { "params": [ "15min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "column": "used_kb",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_mem",
     "query": "select mean(used_kb) from \"router_mem\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "used_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_mem"
    },
    {
     "alias": "buffers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_mem",
     "select": [
      [
       { "params": [ "buffer_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_mem",
     "select": [
      [
       { "params": [ "cached_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "free",
     "column": "free_kb",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_mem",
     "query": "select mean(free_kb) from \"router_mem\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "free_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_mem"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_temp",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "2.4 GHz",
     "column": "temp_24",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_temp",
     "query": "select mean(temp_24) from \"router_temp\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "temp_24" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_temp"
    },
    {
     "alias": "5.0 GHz",
     "column": "temp_50",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_temp",
     "query": "select mean(temp_50) from \"router_temp\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "temp_50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_temp"
    }
   ]
  },
  {
   "title": "Ethernet Bandwidth (eth0)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "eth0_rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "eth0_recv_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "eth0_tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "eth0_trans_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAN Bandwidth (eth0-vlan1)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "wan_rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "wan_recv_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "wan_tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "wan_trans_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LAN Bridge Bandwidth (br0 = vlan1+eth1+eth2)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "br0_rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "br0_recv_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "br0_tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "br0_trans_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LAN Ethernet Bandwidth (vlan1)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "vlan1_rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "vlan1_recv_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "vlan1_tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "vlan1_trans_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LAN Wi-Fi 2.4GHz Bandwidth (eth1)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "eth1_rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "eth1_recv_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "eth1_tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "eth1_trans_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LAN Wi-Fi 5GHz Bandwidth (eth2)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "eth2_rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "eth2_recv_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "eth2_tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "eth2_trans_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VPN Bandwidth (tun21, tun22)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "tun21_rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "tun21_recv_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "tun21_tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "tun21_trans_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "tun22_rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "tun22_recv_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "tun22_tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "tun22_trans_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "eth0_recv_errs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth0_rx_errs" ], "type": "alias" }
      ],
      [
       { "params": [ "eth0_recv_drop" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth0_rx_drop" ], "type": "alias" }
      ],
      [
       { "params": [ "eth0_trans_errs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth0_tx_errs" ], "type": "alias" }
      ],
      [
       { "params": [ "eth0_trans_drop" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth0_tx_drop" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "eth1_recv_errs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth1_rx_errs" ], "type": "alias" }
      ],
      [
       { "params": [ "eth1_recv_drop" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth1_rx_drop" ], "type": "alias" }
      ],
      [
       { "params": [ "eth1_trans_errs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth1_tx_errs" ], "type": "alias" }
      ],
      [
       { "params": [ "eth1_trans_drop" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth1_tx_drop" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "eth2_recv_errs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth2_rx_errs" ], "type": "alias" }
      ],
      [
       { "params": [ "eth2_recv_drop" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth2_rx_drop" ], "type": "alias" }
      ],
      [
       { "params": [ "eth2_trans_errs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth2_tx_errs" ], "type": "alias" }
      ],
      [
       { "params": [ "eth2_trans_drop" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "eth2_tx_drop" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router_net2",
     "select": [
      [
       { "params": [ "vlan1_recv_errs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "vlan1_rx_errs" ], "type": "alias" }
      ],
      [
       { "params": [ "vlan1_recv_drop" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "vlan1_rx_drop" ], "type": "alias" }
      ],
      [
       { "params": [ "vlan1_trans_errs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "vlan1_tx_errs" ], "type": "alias" }
      ],
      [
       { "params": [ "vlan1_trans_drop" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "vlan1_tx_drop" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "External Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "google",
     "column": "ms",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "groupby_field": "dst",
     "measurement": "router_ping_ext",
     "query": "select dst, mean(ms) from \"router_ping_ext\" where $timeFilter group by time($interval), dst order asc",
     "select": [
      [
       { "params": [ "ping_google" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_ping_ext"
    },
    {
     "alias": "nia",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_ping_ext",
     "select": [
      [
       { "params": [ "ping_nia" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wi-Fi Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "2.4 GHz",
     "column": "count",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_assoclist_24",
     "query": "select mean(count) from \"router_assoclist_24\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_assoclist_24"
    },
    {
     "alias": "5.0 GHz",
     "column": "count",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_assoclist_50",
     "query": "select mean(count) from \"router_assoclist_50\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_assoclist_50"
    }
   ]
  }
 ]
}